FID-20 feat: Security, SignIn and SignUp
Filmaro/filmaro-api-backend pull request #5
Opened 2022-09-26 19:40 UTC by vaaaarlos

# 🎬 Filmaro 🎬 - Pull Request

## Description:

This pull request implements security, login and sign-up in the project API. For this, we have created the '/sign-in', '/sign-up' and '/user/me' endpoints. In addition, OAuth2, OIDC and JWT implementation was made.

## Type of change:

Delete this message and use "x" between the square brackets to mark a valid option below.

- [X] New feature (This PR adds a new functionality to the project)
- [ ] Technical debt (This PR improve features already created)
- [ ] Bug fix (This PR covers solving a bug)
- [ ] Documentation (This PR require a documentation update, i.e. the class doc)
- [ ] Issue resolution (This PR solve an github open issue)
  [Link to solved Issue](#IssueLinkGoesHere)

## Checklist:

Delete this message and the options that is unnecessary, i.e. the options that are no relate to the changes you made.

- [X] I followed the concept of clean archtecture.
- [X] I followed the concept of clean code.
- [X] My changes do not generate a new warning or issue.
- [X] I deleted all the code lines that are not being used.
- [ ] I commented my code in some areas i believed that are difficult to understand.

👩🏽‍💻~ Filmaro Team ~👨🏽‍💻

2022-09-27 14:14 UTC, JoaoWudarski requested changes
Reforçando o ponto do clean arch.... Eu posso fazer isso nessa branch mesmo e você revisa depois, já que tu fez ao endpoint de cadastro também...

2022-09-27 14:14 UTC, JoaoWudarski commented on src/main/java/br/com/filmaro/util/ISO8601InstantSerializer.java
> +    private static final DateTimeFormatter DATE_TIME_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss.SSSXXX");
XXX? SexSexSex? Qual o motivo desse XXX no final do pattern? kkkk

2022-09-27 14:14 UTC, JoaoWudarski commented on src/main/resources/application.yaml
> +            client-secret: ${GOOGLE_CLIENT_SECRET}
Localmente, de onde você está sacando essas variáveis de ambiente? Está setando direto na sua máquina?

2022-09-27 14:14 UTC, JoaoWudarski commented on src/main/java/br/com/filmaro/exception/OAuth2AuthenticationProcessingException.java
> +    public OAuth2AuthenticationProcessingException(String msg, Throwable t) {
Sonar está indicando que esse construtor não é utilizado. Além disso essa exception é capturada por qual handler? O padrão lá handleAllException

2022-09-27 14:14 UTC, JoaoWudarski commented on src/main/java/br/com/filmaro/controller/UserController.java
> +    public ResponseEntity<?> getCurrentUser(@CurrentUser UserPrincipal userPrincipal) {
Esse UserPrincipal deveria ganhar um UserPrincipalRequest e ser colocado as validações, né?

2022-09-27 14:14 UTC, JoaoWudarski commented on src/main/java/br/com/filmaro/config/AppProperties.java
> +}
To meio perdido com essa classe... Essa propriedades são usadas onde? E por que não separar essas classes em arquivos separados?

2022-09-30 23:31 UTC, vaaaarlos commented on src/main/java/br/com/filmaro/Application.java
> +    }
Bom saber disso. Resolvido via [2a0f252](https://github.com/Filmaro/filmaro-api-backend/pull/5/commits/2a0f25203dcbba6e123854644f55b6312418e3a7).

2022-09-30 23:32 UTC, vaaaarlos commented on src/main/java/br/com/filmaro/config/SecurityConfig.java
> +    private UserDetailsServiceImpl userDetailsService;
Resolvido via [4b5dcce](https://github.com/Filmaro/filmaro-api-backend/pull/5/commits/4b5dccee04bfdfde470bae054cc0f7e7226d89bc).

2022-09-30 23:36 UTC, vaaaarlos commented on src/main/java/br/com/filmaro/config/SecurityConfig.java
> +    private OAuth2UserServiceImpl oAuth2UserService;
Entendi. Nesse caso, como a classe UserDetailsServiceImpl possui métodos que não fazem parte do contrato da interface UserDetails, faz-se necessário que criemos nossa própria interface X que implemente UserDetails e possua os novos métodos, e o UserDetailsImpl implementará X.

Fica a seu critério resolver ou pedir mudanças para que eu implemente isso.

2022-09-30 23:39 UTC, vaaaarlos commented on src/main/java/br/com/filmaro/config/SecurityConfig.java
> +    private HttpCookieOAuth2AuthorizationRequestRepository httpCookieOAuth2AuthorizationRequestRepository;
Resolvido via [[eeca08d](https://github.com/Filmaro/filmaro-api-backend/pull/5/commits/eeca08d69d5151214fd894de5ebb34f5ac05c701).

2022-09-30 23:39 UTC, vaaaarlos commented on src/main/java/br/com/filmaro/controller/AuthController.java
> +    public ResponseEntity<?> authenticateUser(@Valid @RequestBody SignInRequest loginRequest) {
Resolvido via [65ee7ae](https://github.com/Filmaro/filmaro-api-backend/pull/5/commits/65ee7aeb9963316405134ffba4ed8b5d28cb2ddd).

2022-09-30 23:40 UTC, vaaaarlos commented on src/main/java/br/com/filmaro/util/ISO8601InstantSerializer.java
> +    private static final DateTimeFormatter DATE_TIME_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss.SSSXXX");
X é de timezone.

2022-09-30 23:40 UTC, vaaaarlos commented on src/main/resources/application.yaml
> +            client-secret: ${GOOGLE_CLIENT_SECRET}
Estou armazenando na configuração de build da IDE.

2022-09-30 23:42 UTC, vaaaarlos commented on src/main/java/br/com/filmaro/exception/OAuth2AuthenticationProcessingException.java
> +    public OAuth2AuthenticationProcessingException(String msg, Throwable t) {
Exceções do tipo AuthenticationExcpetion são capturadas pelo handler RestAuthenticationEntryPoint. Resolvido via [eeca08d](https://github.com/Filmaro/filmaro-api-backend/pull/5/commits/eeca08d69d5151214fd894de5ebb34f5ac05c701).

2022-09-30 23:42 UTC, vaaaarlos commented on src/main/java/br/com/filmaro/controller/UserController.java
> +    public ResponseEntity<?> getCurrentUser(@CurrentUser UserPrincipal userPrincipal) {
Este parâmetro não é um request body.

2022-10-01 00:15 UTC, vaaaarlos commented on src/main/java/br/com/filmaro/config/AppProperties.java
> +}
É um método alternativo à utilizar a anotação Value (vide exemplo no código [aqui](https://github.com/Filmaro/filmaro-api-backend/pull/5/files#diff-ed42fba3ed62cf3aab432b0c8bd9c6cc7ce0ec4e22696fead192f0071eb480ffR11)), podemos utilizar esta classe de configuração, [habilitando na aplicação](https://github.com/Filmaro/filmaro-api-backend/pull/5/files#diff-0ae603643e86cdf7b9ae34040438748d680e0059f251d859ce6e1f5086e5887cR14) de modo que possamos acessar valores do application.yaml por meio de getters ao injetar esta classe onde se deseja usar (vide exemplo no código [aqui](https://github.com/Filmaro/filmaro-api-backend/pull/5/files#diff-7b0a2618569b0208742f3ec04c6f3735f8d83143cb6363844ca34330d347b28eR67)).

2022-10-01 00:18 UTC, vaaaarlos commented on src/main/java/br/com/filmaro/controller/AuthController.java
> +    @Setter(onMethod = @__(@Autowired))
Resolvido via [eeca08d](https://github.com/Filmaro/filmaro-api-backend/pull/5/commits/eeca08d69d5151214fd894de5ebb34f5ac05c701).

2022-10-01 00:18 UTC, vaaaarlos commented on src/main/java/br/com/filmaro/controller/AuthController.java
> +@RequestMapping("/auth")
Atualmente não é mais preciso utilizar o @Validated.

2022-10-01 00:19 UTC, vaaaarlos commented on pom.xml
> -            <artifactId>springdoc-openapi-ui</artifactId>
Resolvido via [2a0f252](https://github.com/Filmaro/filmaro-api-backend/pull/5/commits/2a0f25203dcbba6e123854644f55b6312418e3a7).

2022-10-01 00:20 UTC, vaaaarlos commented on src/main/java/br/com/filmaro/controller/AuthController.java
> +    public ResponseEntity<?> registerUser(@Valid @RequestBody SignUpRequest signUpRequest) {
Resolvido via [65ee7ae](https://github.com/Filmaro/filmaro-api-backend/pull/5/commits/65ee7aeb9963316405134ffba4ed8b5d28cb2ddd).

2022-10-01 00:20 UTC, vaaaarlos commented on src/main/java/br/com/filmaro/exception/BadRequestException.java
> +@ResponseStatus(HttpStatus.BAD_REQUEST)
Nice.

2022-10-01 00:26 UTC, vaaaarlos commented on src/main/java/br/com/filmaro/exception/handler/RestAuthenticationEntryPoint.java
> +    private static final Logger logger = LoggerFactory.getLogger(RestAuthenticationEntryPoint.class);
Resolvido via [cc2d33c](https://github.com/Filmaro/filmaro-api-backend/pull/5/commits/cc2d33c849ca2261fda983b06e040cde42ff5848).

2022-10-01 00:26 UTC, vaaaarlos commented on src/main/java/br/com/filmaro/init/ObjectMapperFactory.java
> +}
Singleton pattern.

2022-10-01 00:31 UTC, vaaaarlos commented on src/main/java/br/com/filmaro/model/User.java
> +
Vou rever para separar a entidade da lógica de autenticação.

2022-10-01 00:33 UTC, vaaaarlos commented on src/main/java/br/com/filmaro/security/oauth2/OAuth2AuthenticationFailureHandler.java
> +    HttpCookieOAuth2AuthorizationRequestRepository httpCookieOAuth2AuthorizationRequestRepository;
Resolvido via [eeca08d](https://github.com/Filmaro/filmaro-api-backend/pull/5/commits/eeca08d69d5151214fd894de5ebb34f5ac05c701).

2022-10-01 00:34 UTC, vaaaarlos commented on src/main/java/br/com/filmaro/security/token/TokenAuthenticationFilter.java
> +    private UserDetailsServiceImpl userDetailsService;
Resolvido via [eeca08d](https://github.com/Filmaro/filmaro-api-backend/pull/5/commits/eeca08d69d5151214fd894de5ebb34f5ac05c701) e [cc2d33c](https://github.com/Filmaro/filmaro-api-backend/pull/5/commits/cc2d33c849ca2261fda983b06e040cde42ff5848).

2022-10-01 00:35 UTC, vaaaarlos commented on src/main/java/br/com/filmaro/security/user/UserPrincipal.java
> +    private Collection<? extends GrantedAuthority> authorities;
Utilizamos generics pois o @Getter do lombok está implicitamente fazendo @Override de um getter da interface UserDetails.

2022-10-01 16:44 UTC, JoaoWudarski approved these changes

2022-10-01 16:47 UTC, JoaoWudarski reviewed
Opa Carlão eu vi ai as modificações, e aprovei ae... Bora tocar o barco nessas modificações e vou deixar aquela minha branch de lado, porque não vai dar tempo. Vou subir ela imcompleta no github, apenas para não perder

2022-10-01 16:48 UTC, MatheusFrate approved these changes

2022-10-01 16:59 UTC, Im0tec approved these changes
Acredito na review do mano Wu, aprovado!!!

2022-10-01 17:05 UTC, merged